name: Jalankan AI Rekomendasi Profesi

on:
  push:
    branches:
      - main

jobs:
  run-ai:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependensi
        run: pip install -r requirements.txt

      - name: Jalankan model AI
        run: python ai_rekomendasi_profesi.py 7 6 8  # Angka ini bisa diganti sesuai kebutuhan
